/*
 * Copyright (c) Jim Coles (jameskcoles@gmail.com) 2018 through present.
 *
 * Licensed under the following license agreement:
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Also see the LICENSE file in the repository root directory.
 */
package org.jkcsoft.space.lang.instance;

import org.jkcsoft.space.lang.ast.TypeDefn;

/**
 * Base notion of an index for fast lookup of objects in a Space without
 * the need to fully scan the base object set. Indexes may be defined by the user,
 * define implicitly as is the case for key definitions, or
 * automatically generated by the runtime based on usage of Spaces.
 *
 * <p>A tabular index is defined by a projection of one or more variables
 * associated with a {@link TypeDefn}. The projection
 * may traverse associations of 1-to-1 or m-to-1, but not 1-to-m.
 *
 * <p>A tree index is defined by a projection that traverses one or more 1-to-m
 * {@link org.jkcsoft.space.lang.ast.AssociationDefn}s, from the starting object type.
 * This includes recursive 1-to-m relations.
 *
 * @author Jim Coles
 */
public interface Index {
//    private MetaReference
//    private List<>

}
