/*
 * Copyright (c) Jim Coles (jameskcoles@gmail.com) 2018 through present.
 *
 * Licensed under the following license agreement:
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Also see the LICENSE file in the repository root directory.
 */
package org.jkcsoft.space.lang.instance;

/**
 * Base notion of an index for fast lookup of objects in a Space without
 * the need to fully scan the Space. Indexes may be defined by the user or
 * automatically generated by the runtime based on usage of Spaces.
 *
 * @author Jim Coles
 */
public class Index {

}
